export const ActionTypes = {
  FETCH_RESTAURANTS_LOADING: "FETCH_RESTAURANTS_LOADING",
  FETCH_RESTAURANTS_SUCCESS: "FETCH_RESTAURANTS_SUCCESS",
  FETCH_RESTAURANTS_ERROR: "FETCH_RESTAURANTS_ERROR",
  FETCH_COLLECTIONS_LOADING: "FETCH_COLLECTIONS_LOADING",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_ERROR: "FETCH_COLLECTIONS_ERROR",
  SAVE_TO_COLLECTIONS_LOADING: "SAVE_TO_COLLECTIONS_LOADING",
  SAVE_TO_COLLECTIONS_SUCCESS: "SAVE_TO_COLLECTIONS_SUCCESS",
  SAVE_TO_COLLECTIONS_ERROR: "SAVE_TO_COLLECTIONS_ERROR",
  ADD_COLLECTION_LOADING: "ADD_COLLECTION_LOADING",
  ADD_COLLECTION_SUCCESS: "ADD_COLLECTION_SUCCESS",
  ADD_COLLECTION_ERROR: "ADD_COLLECTION_ERROR",
};

